### ISSUE TITLE
[1.15.2] Crash with itemloader

### ISSUE THREAD

**Issue by winnetrie83** [BrassGoggledCoders/Transport#10]
Hi There,

I was going to try out this mod.
After i set up an itemloader and configured it to load downwards where my minecraft with furnace was waiting, it crashed my game as soon as i put a coal item in the itemloader

This was on the 1.15.2

here is the crashlog: https://pastebin.com/WfYRSFQg

**Comment by SkySom** [comment]
Ah bother I thought I had checked that properly.
