### ISSUE TITLE
Module Configurator bugs

### ISSUE THREAD

**Issue by Nachtflame** [BrassGoggledCoders/Transport#11]
Transport-1.15.2-2.3.0
forge-31.2.20

1- Shift-clicking items (modules) _out_ of the interface, fills all empty slots of the players inventory with full stacks of said item, without removing the item in the interface. Verified with loaders and engines.

2- Breaks instantly but drops itself only when broken w/Pick (The One Probe lists it as 'No Tool' required)
2b- Does NOT drop it's contents when broken, no matter what is used.

**Comment by SkySom** [comment]
It shouldn't drop it's contents, it should save them, so when you place it's still there.

**Comment by SkySom** [comment]
Which... is also not setup right......

**Comment by Nachtflame** [comment]
~~Just tested, and broken one restacked with others in my inv,
rechecked with no others in inv, and it had no contents when replaced.~~

**Comment by FreneticScribbler** [comment]
Uh oh, I copy pasted that code...
