### ISSUE TITLE
Crashing with newer Quark versions

### ISSUE THREAD

**Issue by BlinkGames** [BrassGoggledCoders/Transport#19]
Anytime there is a redstone signal near the cargo cart powered by a solid fuel engine the game crashes. If it's on a holding rail it crashes the server, if it's on a switched rail it crashes the client. I am currently playing Valhesia with another person and as long as they are not in the area they are fine, but as soon as someone enters the area they crash. Quark is installed but apparently the newer version does not help it. We used explosive arrows and a bow to get rid of the items in the area. Interesting mod just can't use it currently.
[crash-2020-12-21_21.02.53-client.txt](https://github.com/BrassGoggledCoders/Transport/files/5727451/crash-2020-12-21_21.02.53-client.txt)

**Comment by sjstark** [comment]
Jumping in on this issue, we're getting crashes (both solo and on our server) whenever a holding rail receives power with a minecart on it (of any type)
Server Crash Logs: https://gist.github.com/sjstark/364f44f4a7c90c335e7d78e6871a8abf

**Comment by SkySom** [comment]
This is correct. most the rails in the mod respect Cart Linking, which links to Quark's code, which they heavily refactored in the newest version. Current work around is completely avoid the rails, or downgrade Quark
