### ISSUE TITLE
[1.12] Crash with Loaders

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/Transport#2]
Forge: 2707
BASE: 3.9.0
Transport: 1.0.0
Crash Report: https://paste.dimdev.org/apacolireq.mccrash

Replicate:
- place a holder rail
- place a loader on top
- configure it with the wrench
- place a hopper on top of the loader
- put an item into the hopper

**Comment by SkySom** [comment]
For now just put a chest between the hopper and the loader and it'll work, but this will be fixed in the next version
