### ISSUE TITLE
[Server Crash] Description: Ticking entity - java.lang.NoClassDefFoundError: vazkii/quark/automation/base/ChainHandler

### ISSUE THREAD

**Issue by Ridanisaurus** [BrassGoggledCoders/Transport#20]
Our server crashed this morning with the following Crash Log, it seems to be related to a compat between Transport and Quark, we think.

Quark Version: Quark-r2.4-281
Transport Verion: Transport-1.16.4-3.3.0
Forge Verion: 35.1.13

Crash Log: https://gist.github.com/Ridanisaurus/cd445b0bafe084c1e18d644759ec95f4

Please let me know if you require any additional information.

**Comment by SkySom** [comment]
Fixed in 3.3.1, just need to update
