### ISSUE TITLE
[3.4.0] Errors in currently selected datapacks prevented world from loading

### ISSUE THREAD

**Issue by nikita488** [BrassGoggledCoders/Transport#21]
Minecraft 1.16.4
Forge 35.1.36
Transport 3.4.0

When trying to load my singleplayer world, I get this screen:
"Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually"
When I downgrade Transport to 3.3.1, it loads fine.

[debug-4.log](https://github.com/BrassGoggledCoders/Transport/files/5800849/debug-4.log)

**Comment by FreneticScribbler** [comment]
Looks like Registrate isn't a fan of you turning off the steam bucket Sky...
Could be cross mod interaction with Thermal's bottler too

**Comment by SteaSteaStea** [comment]
Same issue on world creation:
https://paste.ee/p/1KIxE

**Comment by LlubNek** [comment]
This seems like the right place to leave these:
[latest.log](https://github.com/BrassGoggledCoders/Transport/files/5802131/latest.log)
[crash-2021-01-12_07.39.24-client.txt](https://github.com/BrassGoggledCoders/Transport/files/5802132/crash-2021-01-12_07.39.24-client.txt)

With an existing world I get the datapack error (not sure if that's your fault; it seems to happen whenever I update mods).  With a new world it crashes with an error related to steam buckets.

**Comment by ghost** [comment]
Hello, confirmed here as well, on world creation after adding the following mods:
rftoolsX/rsrequestify/sophisticatedbackpacks/thermalX/tubesreloaded/xnet/xnetgases/mcjtylib

Should I remove transports or thermalX mods for now, or does it matter? thanks

Crash Report: https://pastebin.com/WA5Wvm8V

**Comment by brisingraerowing** [comment]
I put a link to this on the Team CoFH Discord so that they are aware as well.

**Comment by KingLemming** [comment]
The error here seems to be that Transport is not registering their Steam Bucket, but is telling the fluid that it has.

**Comment by SkySom** [comment]
Yep it's on my side. Working on a fix.

**Comment by SkySom** [comment]
Going back to 3.3.x is a fix for now.

**Comment by thakyZ** [comment]
Ah yes I just had this error, thank you @SkySom for saying what the fix would be.

**Comment by SkySom** [comment]
Yep no problem. My hope is to get a fix out tonight.
