### ISSUE TITLE
Module Configurator Crash when installed with Yung's Better Portals

### ISSUE THREAD

**Issue by czbuendel** [BrassGoggledCoders/Transport#34]
When installed with Yung's Better Portals loading a cart into the Module Configurator will cause the instance to freeze requiring a force quit. Checking the log files gives a ticking entity error, which I have attached. [https://pastebin.com/EpF72Jzc](url)

Tried in an instance with just Transport and Better Portals (and their dependencies) to confirm the issue.
Forge 36.0.14 (tried with most up to date 36.0.42 as well, still causes the error)
Transport 1.16.4-3.4.2
Better Portals 1.16.4-0.3

The issue does not exist with Better Portals 1.16.4-0.2.1.
yungnickyoung/YUNGs-Better-Portals#14

**Comment by SkySom** [comment]
I can add some defensive checks, but really they shouldn't be getting and checking Capabilities during the Attach Event.
