### ISSUE TITLE
"Comparator" Assorted routing not working

### ISSUE THREAD

**Issue by tired9494** [BrassGoggledCoders/Transport#37]
COMPARATOR assorted routing is not working. I write the following:
```
ROUTING {
 COMPARATOR {
  3
 }
}
```
but it does not route the modular minecart when it would have a comparator strength of 3 or more. I also tried:
```
ROUTING {
 NOT {
  COMPARATOR {
   3
  }
 }
}
```
to make sure I wasn't incorrect about something. Neither work, but the routing works if I try something else (e.g. name). If I use a normal comparator instead of the lectern then it also works fine. If the comparator routing worked correctly then at least one of the above would route a minecart.

**Comment by SkySom** [comment]
Have you tried riding through the Switch in the cart?

**Comment by SkySom** [comment]
Also what type of cart were you using?

**Comment by SkySom** [comment]
Nevermind I'd dumb it's broken.
