### ISSUE TITLE
[1.16.5-3.5.0] Quark Chests cannot be used in the Modular Configurator

### ISSUE THREAD

**Issue by TwistedGate** [BrassGoggledCoders/Transport#39]
Tried to get into Transport on the IE dev server, but i cannot add a quarks chests.
And on the server the vanilla ones are uncraftable.

Using `forge:chests` instead of the vanilla chest item directly i think should be a good idea

**Comment by SkySom** [comment]
Would be a horrible idea, actually! As all Module's are meant to be one to one with their blocks. A better idea would be to revive the old Quark Compat that had Cargo Modules for all the Quark chests.
