### ISSUE TITLE
Bumper model has a gap

### ISSUE THREAD

**Issue by niraqw** [BrassGoggledCoders/Transport#52]
![Bumper](https://user-images.githubusercontent.com/22210045/133003630-8120454a-637d-4d9c-83de-110b22043a59.png)

Minecraft 1.16.5
Forge 36.2.4
Mods:
Transport 3.7.0
Titanium 3.2.8.5-20
Patchouli 53.1

**Comment by SkySom** [comment]
Fixed in Upcoming 1.18 Release
