### ISSUE TITLE
Game Crashed, the game said it's transport

### ISSUE THREAD

**Issue by thisisACat5** [BrassGoggledCoders/Transport#8]
https://gist.github.com/thisisACat5/78ec3d8a4eaf34c64d72c0f51e2af8ba

**Comment by SkySom** [comment]
I need the actual log. These crashes generally mean that something else crashed earlier.

**Comment by thisisACat5** [comment]
log: https://gist.github.com/thisisACat5/274a71064c32b0fd968b9b408c9c567e

**Comment by SkySom** [comment]
Biomes O plenty is crashing while creating it's music disk. That's the real issue.
